version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk-11
    steps:
      - checkout
      - restore_cache:
          key: algorithms-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: algorithms-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/algorithms.jar