version: 2
jobs:
  build:
    working_directory: ~/studies
    docker:
      - image: circleci/openjdk:13.0.1-jdk-buster-node
    steps:
      - checkout
      - restore_cache:
          key: algorithms-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: algorithms-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: algorithms/target/surefire-reports
      - store_artifacts:
          path: algorithms/target/algorithms.jar